---
title: "R Notebook"
output: html_notebook
---

```{r}
install.packages("dplyr")
install.packages("plyr")
install.packages("ggplot2")
install.packages("tidyr")
install.packages("purrr")
install.packages("readr")
install.packages("sqldf")
```

#Libraries needed:

```{r}
library(dplyr)
library(plyr)
library(ggplot2)
library(tidyr)
library(purrr)
library(readr)
library(sqldf)
```


```{r}
articles1 <- read_csv('publishers.csv')
articles2 <- read_csv('paragraphs.csv')
timedelta <- read_csv('timedelta.csv')

articles = merge(x= articles2, y=articles1, by="id") ##only shows the ones with change by default
articles_all = merge(x=articles2, y=articles1, by="id", all=T) ##shows all articles
articles_all_distinct = sqldf("select distinct(id),publisher,url,paragraphs_changed,paragraphs_added,paragraphs_removed from articles_all")

art_changed = sqldf("select id,publisher,edit_distance from articles where sentiment_1!=0 and sentiment_2!=0")

articles_all_distinct_count <- articles_all_distinct%>%group_by(publisher)%>%dplyr::mutate(count=n())
articles_all_distinct_count2 = sqldf("select distinct(publisher),count from articles_all_distinct_count")
articles_all_distinct_count2<-na.omit(articles_all_distinct_count2)
articles_all_distinct_count2<-articles_all_distinct_count2[-c(18),]
#get article change count per pub
art_all_changed = sqldf("select distinct(id),publisher from articles where (sentiment_1 !=0 or sentiment_2 != 0)")
art_all_changed<-art_all_changed%>%group_by(publisher)%>%dplyr::mutate(count=n())
art_all_changed2 = sqldf("select distinct(publisher),count from art_all_changed")
art_all_changedx=merge(x=art_all_changed2,y=articles_all_distinct_count2,by="publisher")

art_all_changedx$changed_pct<-(art_all_changedx$count.x/art_all_changedx$count.y)*100
art_changed=merge(x=art_changed,y=art_all_changedx,by="publisher")

ggplot(data=art_changed, mapping=aes(x=reorder(publisher,-changed_pct),y=edit_distance,fill=changed_pct,order=changed_pct))+geom_boxplot(outlier.shape=NA)+scale_fill_gradient(low="green",high="red")+coord_flip()+theme_bw()+theme(axis.title=element_text(face="bold",size=14),axis.text.x=element_text(size=10),legend.text=element_text(size=10,angle=45),legend.title=element_text(face="bold",size=14),legend.position="top")+labs(x="Publisher",y="Edit Distance",fill="% of changed articles")


```